services:
  app:
    container_name: fastapi
    build:
      context: ..
      dockerfile: provision/Dockerfile.dev
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ../src:/app/src