services:
  app:
    container_name: fastapi
    build:
      context: ..
      dockerfile: provision/Dockerfile.dev
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ../src:/app/src
    environment:
      - DEV=1
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - harfanglab-test:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  harfanglab-test: