"""Recreate schema

Revision ID: 27a6a047be5f
Revises: 
Create Date: 2026-06-09 17:39:37.038387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '27a6a047be5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videogame',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('ratings', sa.Integer(), nullable=True),
    sa.Column('studio', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('platform', sa.JSON(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videogame')
    # ### end Alembic commands ###
